# Dependabot configuration for Vintage Store multi-module project
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Agent Code Sample module
  - package-ecosystem: "maven"
    directory: "/agent-code-sample"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "agoncal"
    commit-message:
      prefix: "deps(agent-code-sample)"
      include: "scope"
    labels:
      - "dependencies"
      - "maven"
      - "agent-code-sample"

  # Commons module
  - package-ecosystem: "maven"
    directory: "/commons"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "agoncal"
    commit-message:
      prefix: "deps(commons)"
      include: "scope"
    labels:
      - "dependencies"
      - "maven"
      - "commons"

  # Agent Reference module
  - package-ecosystem: "maven"
    directory: "/agent-reference"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "agoncal"
    commit-message:
      prefix: "deps(agent-reference)"
      include: "scope"
    labels:
      - "dependencies"
      - "maven"
      - "agent-reference"

  # Agent Release module
  - package-ecosystem: "maven"
    directory: "/agent-release"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "agoncal"
    commit-message:
      prefix: "deps(agent-release)"
      include: "scope"
    labels:
      - "dependencies"
      - "maven"
      - "agent-release"

  # Agent Statistics module
  - package-ecosystem: "maven"
    directory: "/agent-statistics"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "agoncal"
    commit-message:
      prefix: "deps(agent-statistics)"
      include: "scope"
    labels:
      - "dependencies"
      - "maven"
      - "agent-statistics"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "agoncal"
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"